services:
    meetaiapp:
        container_name: meetaiapp
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        depends_on:
            - meetaidb
        ports:
            - '${FRONT_PORT}:3000'
        environment:
            - NODE_ENV=development
        networks:
            - default
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        volumes:
            - .:/app
            - /app/node_modules

    meetaidb:
        container_name: meetaidb
        image: postgres:15-alpine
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_HOST=${DB_HOST}
        restart: unless-stopped
        ports:
            - '5432:5432'
        networks:
            - default

networks:
    default:
