# Utiliser l'image de base Node.js
FROM node:20-alpine

# Add this line to install mysql-client
RUN apk add --no-cache mysql-client

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et yarn.lock (ou package-lock.json si tu utilises npm)
COPY package*.json yarn.lock ./

# Installer les dépendances
RUN yarn

# Préparer Husky
RUN yarn prepare

# Copier le reste de l'application
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Commande pour lancer l'application en mode développement
CMD ["yarn", "dev"]
