# Utiliser l'image de base Node.js
FROM node:20-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier le reste de l'application
COPY . .

# Installer les dépendances
RUN yarn

# Préparer Husky
RUN yarn prepare

# Exposer le port 3000
EXPOSE 3000

# Commande pour lancer l'application en mode développement
CMD ["yarn", "dev"]
